import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { Config, Context, Effect, Layer, Schema } from "effect";

/** A stored image could not be written or read back. */
export class ImageStorageFailure extends Schema.TaggedError<ImageStorageFailure>()(
  "ImageStorageFailure",
  {
    key: Schema.String,
    message: Schema.String,
  },
) {}

export interface StoredImage {
  readonly bytes: Uint8Array;
  readonly contentType: string;
}

/**
 * Where uploaded images live. Deliberately narrow so the local-disk layer used
 * in development can be swapped for object storage without touching callers,
 * and so tests never reach a third-party service.
 */
export class ImageStorage extends Context.Service<
  ImageStorage,
  {
    readonly put: (key: string, image: StoredImage) => Effect.Effect<void, ImageStorageFailure>;
    readonly get: (key: string) => Effect.Effect<StoredImage, ImageStorageFailure>;
  }
>()("@home-bird/ImageStorage") {
  static readonly put = (key: string, image: StoredImage) =>
    Effect.flatMap(ImageStorage, (storage) => storage.put(key, image));
  static readonly get = (key: string) =>
    Effect.flatMap(ImageStorage, (storage) => storage.get(key));

  /** Local disk, rooted at IMAGE_STORAGE_DIR. */
  static readonly layer = Layer.effect(
    ImageStorage,
    Effect.gen(function* () {
      const root = resolve(
        yield* Config.string("IMAGE_STORAGE_DIR").pipe(Config.withDefault("./.data/images")),
      );

      // Keys are generated by the api, never by the client, but resolve anyway
      // so a key can never escape the storage root.
      const pathFor = (key: string) => {
        const path = resolve(join(root, key));
        return path.startsWith(root) ? path : undefined;
      };

      const fail = (key: string) => (cause: unknown) =>
        new ImageStorageFailure({ key, message: String(cause) });

      const put = Effect.fn("ImageStorage.put")(function* (key: string, image: StoredImage) {
        const path = pathFor(key);
        if (path === undefined) {
          return yield* new ImageStorageFailure({ key, message: "invalid storage key" });
        }
        yield* Effect.tryPromise({
          try: async () => {
            await mkdir(dirname(path), { recursive: true });
            await writeFile(path, image.bytes);
            await writeFile(`${path}.type`, image.contentType, "utf8");
          },
          catch: fail(key),
        });
      });

      const get = Effect.fn("ImageStorage.get")(function* (key: string) {
        const path = pathFor(key);
        if (path === undefined) {
          return yield* new ImageStorageFailure({ key, message: "invalid storage key" });
        }
        return yield* Effect.tryPromise({
          try: async (): Promise<StoredImage> => ({
            bytes: new Uint8Array(await readFile(path)),
            contentType: await readFile(`${path}.type`, "utf8"),
          }),
          catch: fail(key),
        });
      });

      return { put, get };
    }),
  );

  /** In-memory implementation for tests — no filesystem, no object storage. */
  static readonly testLayer = Layer.sync(ImageStorage, () => {
    const store = new Map<string, StoredImage>();
    return {
      put: (key, image) => Effect.sync(() => void store.set(key, image)),
      get: (key) =>
        Effect.suspend(() => {
          const image = store.get(key);
          return image === undefined
            ? new ImageStorageFailure({ key, message: "not found" })
            : Effect.succeed(image);
        }),
    };
  });
}
